consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  GoaNewsApiArticle:
    description: 記事詳細のデータ (default view)
    example:
      clicks: 3.317074e+18
      description: Ratione odio magnam.
      head_line: Qui est ipsam.
      id: 7.1909056e+18
    properties:
      clicks:
        example: 3.317074e+18
        format: int64
        type: integer
      description:
        example: Ratione odio magnam.
        type: string
      head_line:
        example: Qui est ipsam.
        type: string
      id:
        example: 7.1909056e+18
        format: int64
        type: integer
    required:
    - id
    - head_line
    - description
    - clicks
    title: 'Mediatype identifier: application/vnd.goa.news.api.article+json; view=default'
    type: object
  GoaNewsApiArticleCollection:
    description: GoaNewsApiArticleCollection is the media type for an array of GoaNewsApiArticle
      (default view)
    example:
    - clicks: 3.317074e+18
      description: Ratione odio magnam.
      head_line: Qui est ipsam.
      id: 7.1909056e+18
    items:
      $ref: '#/definitions/GoaNewsApiArticle'
    title: 'Mediatype identifier: application/vnd.goa.news.api.article+json; type=collection;
      view=default'
    type: array
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
host: localhost:18080
info:
  contact:
    email: m153304w@st.u-gakugei.ac.jp
    name: shu920921
    url: https://github.com/shu920921/goa_news_api/issues
  description: goaを用いたnews apiのサンプル
  license:
    name: MIT
  title: news api sample
  version: ""
paths:
  /api/v1/articles/:
    get:
      description: 記事の一覧
      operationId: articles#articles
      produces:
      - application/vnd.goa.error
      - application/vnd.goa.news.api.article+json; type=collection
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GoaNewsApiArticleCollection'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      - https
      summary: articles articles
      tags:
      - articles
  /api/v1/articles/{id}:
    get:
      description: 記事の詳細
      operationId: articles#article
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/vnd.goa.error
      - application/vnd.goa.news.api.article+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GoaNewsApiArticle'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
      schemes:
      - http
      - https
      summary: article articles
      tags:
      - articles
  /swagger.json:
    get:
      operationId: swagger#/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
      - https
      summary: Download swagger/swagger.json
  /swagger/{filepath}:
    get:
      operationId: swagger#/swagger/*filepath
      parameters:
      - description: Relative file path
        in: path
        name: filepath
        required: true
        type: string
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
        "404":
          description: File not found
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      - https
      summary: Download public/swagger/
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  NotFound:
    description: Not Found
schemes:
- http
- https
swagger: "2.0"
