// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "news api": Application Media Types
//
// Command:
// $ goagen
// --design=news-api/design
// --out=$(GOPATH)/src/news-api
// --version=v1.2.0-dirty

package app

import (
	"github.com/goadesign/goa"
)

// 記事詳細のデータ (default view)
//
// Identifier: application/vnd.goa.news.api.article+json; view=default
type GoaNewsAPIArticle struct {
	Clicks      int    `form:"clicks" json:"clicks" xml:"clicks"`
	Description string `form:"description" json:"description" xml:"description"`
	HeadLine    string `form:"head_line" json:"head_line" xml:"head_line"`
	ID          int    `form:"id" json:"id" xml:"id"`
}

// Validate validates the GoaNewsAPIArticle media type instance.
func (mt *GoaNewsAPIArticle) Validate() (err error) {

	if mt.HeadLine == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "head_line"))
	}
	if mt.Description == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "description"))
	}

	return
}

// GoaNewsApiArticleCollection is the media type for an array of GoaNewsApiArticle (default view)
//
// Identifier: application/vnd.goa.news.api.article+json; type=collection; view=default
type GoaNewsAPIArticleCollection []*GoaNewsAPIArticle

// Validate validates the GoaNewsAPIArticleCollection media type instance.
func (mt GoaNewsAPIArticleCollection) Validate() (err error) {
	for _, e := range mt {
		if e != nil {
			if err2 := e.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	return
}
