// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "news api": Application User Types
//
// Command:
// $ goagen
// --design=news-api/design
// --out=$(GOPATH)/src/news-api
// --version=v1.2.0-dirty

package app
